version: "3.8"
services:
  dms_app:
    container_name: dms_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - dms_db
    networks:
      - app_network

  dms_nginx:
    container_name: dms_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - dms_app
    environment:
      NGINX_FPM_HOST: dms_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  dms_db:
    container_name: dms_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network


networks:
  app_network:
    driver: bridge